package br.thiago.habitflowapp.presentation.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF226A4C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF10b981)
val onPrimaryContainerLight = Color(0xFF005236)
val secondaryLight = Color(0xFF4D6357)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E8D8)
val onSecondaryContainerLight = Color(0xFF364B40)
val tertiaryLight = Color(0xFF3D6473)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC0E9FB)
val onTertiaryContainerLight = Color(0xFF244C5A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF5)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF5FBF5)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFDCE5DD)
val onSurfaceVariantLight = Color(0xFF404943)
val outlineLight = Color(0xFF707973)
val outlineVariantLight = Color(0xFFC0C9C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322E)
val inverseOnSurfaceLight = Color(0xFFEDF2EC)
val inversePrimaryLight = Color(0xFF8ED5B0)
val surfaceDimLight = Color(0xFFD6DBD6)
val surfaceBrightLight = Color(0xFFF5FBF5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EF)
val surfaceContainerLight = Color(0xFFEAEFE9)
val surfaceContainerHighLight = Color(0xFFE4EAE4)
val surfaceContainerHighestLight = Color(0xFFDEE4DE)



val primaryDark = Color(0xFF8ED5B0)
val onPrimaryDark = Color(0xFF003824)
val primaryContainerDark = Color(0xFF005236)
val onPrimaryContainerDark = Color(0xFFAAF2CC)
val secondaryDark = Color(0xFFB4CCBD)
val onSecondaryDark = Color(0xFF20352A)
val secondaryContainerDark = Color(0xFF364B40)
val onSecondaryContainerDark = Color(0xFFD0E8D8)
val tertiaryDark = Color(0xFFA5CDDE)
val onTertiaryDark = Color(0xFF063543)
val tertiaryContainerDark = Color(0xFF244C5A)
val onTertiaryContainerDark = Color(0xFFC0E9FB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDEE4DE)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDEE4DE)
val surfaceVariantDark = Color(0xFF404943)
val onSurfaceVariantDark = Color(0xFFC0C9C1)
val outlineDark = Color(0xFF8A938C)
val outlineVariantDark = Color(0xFF404943)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DE)
val inverseOnSurfaceDark = Color(0xFF2C322E)
val inversePrimaryDark = Color(0xFF226A4C)
val surfaceDimDark = Color(0xFF0F1511)
val surfaceBrightDark = Color(0xFF353B37)
val surfaceContainerLowestDark = Color(0xFF0A0F0C)
val surfaceContainerLowDark = Color(0xFF171D19)
val surfaceContainerDark = Color(0xFF1B211D)
val surfaceContainerHighDark = Color(0xFF262B28)
val surfaceContainerHighestDark = Color(0xFF303632)





